replicaCount: 1

service:
  type: ClusterIP
  port: 5601

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 6.2.4
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - kibana.dev
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}
