apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname.fluentd-elasticsearch" . }}
  labels:
    app: {{ template "name.fluentd-elasticsearch" . }}
    release: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname.fluentd-elasticsearch" . }}
  labels:
    app: {{ template "name.fluentd-elasticsearch" . }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname.fluentd-elasticsearch" . }}
  labels:
    app: {{ template "name.fluentd-elasticsearch" . }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname.fluentd-elasticsearch" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ template "fullname.fluentd-elasticsearch" . }}
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname.fluentd-elasticsearch" . }}
  labels:
    app: {{ template "name.fluentd-elasticsearch" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name.fluentd-elasticsearch" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name.fluentd-elasticsearch" . }}
        release: {{ .Release.Name }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: {{ template "fullname.fluentd-elasticsearch" . }}
      containers:
      - name: {{ template "fullname.fluentd-elasticsearch" . }}
        image: "{{ .Values.fluentd-elasticsearch.image.repository }}:{{ .Values.fluentd-elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.fluent-delasticsearch.image.pullPolicy }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
          resources:
{{ toYaml .Values.elasticsearch.resources | indent 12 }}
    {{- with .Values.kibana.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.kibana.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.kibana.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: {{ template "fullname.fluentd-elasticsearch" . }}-config
