apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana-logging
  labels:
    k8s-app: {{ .Release.Name }}-kibana-logging
    kubernetes.io/name: "Kibana"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: {{ .Release.Name }}-kibana-logging
