apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana-logging
  labels:
    k8s-app: {{ .Release.Name }}-kibana-logging
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-kibana-logging
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}-kibana-logging
    spec:
      containers:
      - name: {{ .Release.Name }}-kibana-logging
        image: docker.elastic.co/kibana/kibana:6.2.4
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://{{ .Release.Name }}-elasticsearch-logging:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
